// Client-side Word (.docx) report generator. docx is dynamically imported in
// the handler so it stays out of the main bundle until a report is requested.
import type { DatasetProfile } from "./profile";
import type { ResearchReport } from "./research";

export async function generateReportDocx(
  meta: { name: string },
  p: DatasetProfile, r: ResearchReport,
  drafts: { title: string; text: string }[],
  aiReport: string | null
): Promise<Blob> {
  const {
    Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType,
  } = await import("docx");

  const clay = "D97757", ink = "141413", sub = "6B6862";

  const H1 = (t: string) => new Paragraph({
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 280, after: 120 },
    children: [new TextRun({ text: t, color: ink, bold: true })],
  });
  const para = (t: string) => new Paragraph({
    spacing: { after: 100 },
    children: [new TextRun({ text: t, color: ink })],
  });
  const item = (t: string) => new Paragraph({
    bullet: { level: 0 }, spacing: { after: 40 },
    children: [new TextRun({ text: t, color: ink })],
  });
  const kv = (k: string, v: string) => new Paragraph({
    bullet: { level: 0 }, spacing: { after: 40 },
    children: [new TextRun({ text: `${k}: `, bold: true, color: ink }), new TextRun({ text: v, color: ink })],
  });

  const children: InstanceType<typeof Paragraph>[] = [];

  // title block
  children.push(new Paragraph({
    spacing: { after: 40 },
    children: [new TextRun({ text: "Himay Data Validation Report", bold: true, size: 36, color: clay })],
  }));
  children.push(new Paragraph({
    spacing: { after: 240 },
    children: [
      new TextRun({ text: `Dataset: ${meta.name}`, color: sub, size: 20 }),
      new TextRun({ text: `   •   Generated ${new Date().toLocaleString()}`, color: sub, size: 20 }),
    ],
  }));

  // scores
  children.push(H1("Scores"));
  children.push(kv("Himay Score (data quality)", `${p.score}/100 — ${p.grade}`));
  children.push(kv("Research Readiness", `${r.readinessScore}/100 — ${r.readinessBand}`));

  // overview
  children.push(H1("Overview"));
  children.push(kv("Rows", `${p.rows}`));
  children.push(kv("Valid responses (after de-duplication)", `${r.validResponses}`));
  children.push(kv("Columns", `${p.cols}`));
  children.push(kv("Missing values", `${p.totalMissing} (${p.missingPct.toFixed(1)}%)`));
  children.push(kv("Duplicate rows", `${p.duplicates} (${p.dupPct.toFixed(1)}%)`));
  children.push(kv("Likert items detected", `${r.likert.length}`));

  // integrity
  children.push(H1("Survey Integrity"));
  children.push(kv("Straight-lined responses", r.likert.length >= 3 ? `${r.straightLiners}` : "n/a"));
  children.push(kv("Low-variance responses", r.likert.length >= 3 ? `${r.lowVariance}` : "n/a"));
  if (r.invalidFlags.length) {
    children.push(para("Invalid-value flags:"));
    r.invalidFlags.forEach((f) =>
      children.push(item(`${f.column}: ${f.issue} (${f.count}; e.g. ${f.examples.join(", ")})`)));
  } else {
    children.push(item("No invalid values detected."));
  }

  // likert
  if (r.likert.length) {
    children.push(H1("Likert Items"));
    r.likert.forEach((l) =>
      children.push(item(`${l.name} (1–${l.scale}): mean ${l.mean.toFixed(2)}, median ${l.median}, SD ${l.std.toFixed(2)}`)));
  }

  // statistical readiness
  children.push(H1("Statistical Readiness"));
  r.statTests.forEach((t) => children.push(kv(`${t.suitable ? "✓" : "✗"} ${t.name}`, t.note)));

  // ai review (parse light markdown)
  if (aiReport) {
    children.push(H1("AI Research Review"));
    aiReport.split("\n").forEach((line) => {
      const t = line.trim();
      if (!t) return;
      const clean = t.replace(/\*\*/g, "");
      if (t.startsWith("###") || (/^\d+\.\s/.test(t) && t.length < 60)) {
        children.push(new Paragraph({
          heading: HeadingLevel.HEADING_2, spacing: { before: 160, after: 80 },
          children: [new TextRun({ text: clean.replace(/^#+\s*/, "").replace(/^\d+\.\s*/, ""), bold: true, color: ink })],
        }));
      } else if (/^[-*]\s/.test(t)) {
        children.push(item(clean.replace(/^[-*]\s/, "")));
      } else {
        children.push(para(clean));
      }
    });
  }

  // methodology
  if (drafts.length) {
    children.push(H1("Methodology Drafts"));
    drafts.forEach((d) => {
      children.push(new Paragraph({
        spacing: { before: 120, after: 60 },
        children: [new TextRun({ text: d.title, bold: true, color: ink })],
      }));
      children.push(new Paragraph({
        spacing: { after: 120 },
        children: [new TextRun({ text: d.text, italics: true, color: sub })],
      }));
    });
  }

  children.push(new Paragraph({
    spacing: { before: 280 }, alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: "Generated by Himay — validate your data before you trust it.", color: sub, size: 16, italics: true })],
  }));

  const doc = new Document({ sections: [{ children }] });
  return Packer.toBlob(doc);
}
